package com.winning.mobileclinical.model.cis;

import java.math.BigDecimal;
import java.util.List;

import org.json.JSONException;
import org.json.JSONObject;

public class PatBasicInfo {// / <summary>
	// / 病历号
	// / </summary>
	public String blh;
	// / <summary>
	// / 婚姻状况代码
	// / </summary>
	public String hyzkdm;
	// / <summary>
	// / 婚姻状况名称
	// / </summary>
	public String hyzkmc;
	// / <summary>
	// / 民族代码
	// / </summary>
	public String mzdm;
	// / <summary>
	// / 民族名称
	// / </summary>
	public String mzmc;
	// / <summary>
	// / 国籍代码
	// / </summary>
	public String gjdm;
	// / <summary>
	// / 国籍名称
	// / </summary>
	public String gjmc;
	// / <summary>
	// / 文化程度
	// / </summary>
	public String whcd;
	// / <summary>
	// / 教育年限
	// / </summary>
	public int jynx;
	// / <summary>
	// / 出生地代码
	// / </summary>
	public String csddm;
	// / <summary>
	// / 出生地名称
	// / </summary>
	public String csdmc;
	// / <summary>
	// / 出生区县代码
	// / </summary>
	public String csqxdm;
	// / <summary>
	// / 出生区县名称
	// / </summary>
	public String csqxmc;
	// / <summary>
	// / 籍贯省市代码
	// / </summary>
	public String jgssdm;
	// / <summary>
	// / 籍贯省市名称
	// / </summary>
	public String jgssmc;
	// / <summary>
	// / 籍贯区县代码
	// / </summary>
	public String jgqxdm;
	// / <summary>
	// / 籍贯区县名称
	// / </summary>
	public String jgqxmc;
	// / <summary>
	// / 职业代码
	// / </summary>
	public String job_code;
	// / <summary>
	// / 职业名称
	// / </summary>
	public String job_name;
	// / <summary>
	// / 工作单位
	// / </summary>
	public String gzdw;
	// / <summary>
	// / 工作单位地址
	// / </summary>
	public String gzdwdz;
	// / <summary>
	// / 工作单位电话
	// / </summary>
	public String gzdwdh;
	// / <summary>
	// / 工作单位邮编
	// / </summary>
	public String gzdwyb;
	// / <summary>
	// / 户口地址
	// / </summary>
	public String hkdz;
	// / <summary>
	// / 户口联系电话
	// / </summary>
	public String hkdh;
	// / <summary>
	// / 现住地址省市代码
	// / </summary>
	public String xzdzdm;
	// / <summary>
	// / 现住地址省市名称
	// / </summary>
	public String xzdzmc;
	// / <summary>
	// / 现住区县代码
	// / </summary>
	public String xzqxdm;
	// / <summary>
	// / 现住区县名称
	// / </summary>
	public String xzqxmc;
	// / <summary>
	// / 现住地址街道
	// / </summary>
	public String xzdzjd;
	// / <summary>
	// / 现住地址联系电话
	// / </summary>
	public String xzlxdh;
	// / <summary>
	// / 现住地址邮编
	// / </summary>
	public String xzdzyb;
}
